import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/navbar'
import { AptosProvider } from '@/components/aptos-provider'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Aptos WebXR',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<AptosProvider>
			<html lang='en'>
				<head>
					<Script src='https://aframe.io/releases/1.5.0/aframe.min.js'></Script>
				</head>
				<body className={inter.className}>
					<Navbar />
					{children}
				</body>
			</html>
		</AptosProvider>
	)
}
